<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="6" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="3620" started-at="2019-05-07T16:31:31Z" finished-at="2019-05-07T16:31:34Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="3620" started-at="2019-05-07T16:31:31Z" finished-at="2019-05-07T16:31:34Z">
      <class name="com.sample.test.demo.tests.PizzaOrderTest">
        <test-method status="PASS" signature="init()[pri:0, instance:com.sample.test.demo.tests.PizzaOrderTest@3159c4b8]" name="init" is-config="true" duration-ms="2668" started-at="2019-05-07T16:31:31Z" finished-at="2019-05-07T16:31:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="selectPizza()[pri:0, instance:com.sample.test.demo.tests.PizzaOrderTest@3159c4b8]" name="selectPizza" duration-ms="75" started-at="2019-05-07T16:31:33Z" finished-at="2019-05-07T16:31:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectPizza -->
        <test-method status="PASS" signature="vaarifyQuantity()[pri:0, instance:com.sample.test.demo.tests.PizzaOrderTest@3159c4b8]" name="vaarifyQuantity" duration-ms="166" started-at="2019-05-07T16:31:33Z" finished-at="2019-05-07T16:31:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- vaarifyQuantity -->
        <test-method status="FAIL" signature="validateDialog()[pri:0, instance:com.sample.test.demo.tests.PizzaOrderTest@3159c4b8]" name="validateDialog" duration-ms="40" started-at="2019-05-07T16:31:33Z" finished-at="2019-05-07T16:31:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Missing email] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Missing email] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.sample.test.demo.tests.PizzaOrderTest.validateDialog(PizzaOrderTest.java:71)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDialog -->
        <test-method status="PASS" signature="validateEmail()[pri:0, instance:com.sample.test.demo.tests.PizzaOrderTest@3159c4b8]" name="validateEmail" duration-ms="260" started-at="2019-05-07T16:31:33Z" finished-at="2019-05-07T16:31:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateEmail -->
        <test-method status="PASS" signature="validateOrder()[pri:0, instance:com.sample.test.demo.tests.PizzaOrderTest@3159c4b8]" name="validateOrder" duration-ms="120" started-at="2019-05-07T16:31:34Z" finished-at="2019-05-07T16:31:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateOrder -->
        <test-method status="PASS" signature="validatePayment()[pri:0, instance:com.sample.test.demo.tests.PizzaOrderTest@3159c4b8]" name="validatePayment" duration-ms="150" started-at="2019-05-07T16:31:34Z" finished-at="2019-05-07T16:31:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatePayment -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.sample.test.demo.tests.PizzaOrderTest@3159c4b8]" name="tearDown" is-config="true" duration-ms="102" started-at="2019-05-07T16:31:34Z" finished-at="2019-05-07T16:31:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.sample.test.demo.tests.PizzaOrderTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
